sync: hosted cloud (#1207)
<!-- This is an auto-generated comment: release notes by OSS CodeRabbit
-->
### Summary by CodeRabbit

**Refactor:**
- Updated the import path for `DatasheetActions` across multiple files
for better code organization.
- Removed unused `ResourceModel` class from `resource.ts`.
- Removed unused function `setViewStyle2Action` from `KanbanView` class.

**Chore:**
- Added `staticPageGenerationTimeout` configuration in `next.config.js`
to prevent timeout errors.
- Appended a version query parameter to script source in `_document.tsx`
for cache busting.
- Added new environment variable `MAIL_FROM` in Dockerfile.

> 🎉 Code's been shifted, cleaned, and pruned, 🧹🔧  
> Import paths updated, no more marooned. 🚀  
> Timeout tackled, cache always renewed, 🔄  
> With every refactor, our strength is tuned! 💪🎊

<!-- end of auto-generated comment: release notes by OSS CodeRabbit -->

---------

Signed-off-by: William Chan <root@williamchan.me>
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: wangkailang <wangkailang@vikadata.com>
Co-authored-by: William Chan <root@williamchan.me>
Co-authored-by: plodsoft <xplzjwz@gmail.com>
Co-authored-by: Caedman Ziwen Lan <lanziwen@apitable.com>
Co-authored-by: liuyi <liuyi@vikadata.com>
Co-authored-by: Aria <sujian@apitable.com>
Co-authored-by: Chambers <chenbochao@vikadata.com>
Co-authored-by: Kilian <wangkailang@users.noreply.github.com>
Co-authored-by: ziqiang <zhaozhiqiang@vikadata.com>
Co-authored-by: Evie <huangwanmei@apitable.com>
Co-authored-by: Shawn Deng <dengguiheng@apitable.com>
Co-authored-by: Evie Wanmei Huang <37546178+wmEvie@users.noreply.github.com>
Co-authored-by: Michael Xiaoliang Chan <mcl_chan@sina.com>
Co-authored-by: Kelly Chan <kelly@apitable.com>
Co-authored-by: wangkailang <wangkailang@vikadata.com>
Co-authored-by: Kelly Peilin Chan <kelly@vikadata.com>
Co-authored-by: ziqiang <1694392889@qq.com>
Co-authored-by: Dage Zhifeng Wang <46173896+dage233@users.noreply.github.com>
Co-authored-by: Kelvin <panjiawen@vikadata.com>
Co-authored-by: Michael Xiaoliang Chan <111508006+yo-ooiii@users.noreply.github.com>
Co-authored-by: XuKecheng <wsad8254695@outlook.com>
Co-authored-by: Xiaoyue Lin <36526527+100gle@users.noreply.github.com>
Co-authored-by: 100gle <loogle.space@gmail.com>
Co-authored-by: Kelvin Jiawen Pan <panjiawen@apitable.com>
Co-authored-by: Bron ZiJing Liu <liuzijing@vikadata.com>
Co-authored-by: chenguofeng <1508194634@qq.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Harry Yep <git@hode.co.uk>
Co-authored-by: Guofeng Chen <66124783+functionChenGuoFeng@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: magic conch <38741725+Enternalcode@users.noreply.github.com>
Co-authored-by: Binson <zoubingshun@aitable.ai>
Co-authored-by: Binson <zoubingshun1@apitable.com>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,17 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
-#. "$(dirname "$0")/_/husky.sh"
+. "$(dirname "$0")/_/husky.sh"
 
 # npx lint-staged
+
+function check_forbidden_folder() {
+  local forbidden_folder=$1
+
+  if git diff --cached --name-only | grep -q $forbidden_folder; then
+    echo "Error: Files in $forbidden_folder cannot be committed"
+    exit 1
+  fi
+
+}
+
+# check_forbidden_folder "packages/core/src/model"
